GOOGLE_API_KEY="AIzaSyA8fgDqxsQMS0t6R81kdK6ssuatONWja20"
CHROMA_API_KEY="ck-DfDm7DgdRmidKoeF7u17BLXUj7pdfhYoT2DXwjWhrUTv"
CHROMA_TENANT="11e11940-7d24-45b0-b94f-c9a11fbca098"
CHROMA_DB="RAGModelFIass"
